#!/bin/bash
# will pull usefull information for a device

clear

# To get the date
devicedate=`cat /full/path/to/log | grep $1 | tail | grep firstfive | tail -n 1 | grep -Eo '[[:digit:]]{4}-[[:digit:]]{2}-[[:digit:]]{2}'`

# To get the time
devicetime=`cat /full/path/to/log | grep $1 | tail | grep firstfive | tail -n 1 | grep -o 'T[0-9][0-9]:[0-9}' | tr -d ':''\''T'`

# To get IMEI
deviceimei=`cat /full/path/to/log | grep $1 | tail | grep firstfive | tail -n 1 | grep -Eo '[0-9]{15}'`

# To get IP1
ip1=`cat /full/path/to/log | grep $1 | tail | grep firstfive | tail -n 1 | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}

echo "Device information for $deviceimei"
echo ""
echo "Date: $devicedate"
echo "Time: $devicetime"
echo "IP: $ip1"

# TODO
# option to do a tail or a tail -f for more information
